### ISSUE TITLE
JSON formatter showing hashkey

### ISSUE THREAD

**Issue by andrewboni** [mohsen1/json-formatter#21]
Hi, first of all, this is an excellent angular directive. One issue that I'm seeing though is that it displays the `hashKey` when used within an `ng-repeat` directive. See here:

![screenshot 2015-02-13 11 39 12](https://cloud.githubusercontent.com/assets/255026/6194012/2b8d4fd4-b375-11e4-8543-c802b0639896.png)

Is there an easy way to prevent this property from displaying?

**Comment by mohsen1** [comment]
This is certainly a bug in JSON Formatter but you can get around it by using `angular.copy`

```html
<json-formatter json="angular.copy(myJson)"></json-formatter>
```

**Comment by andrewboni** [comment]
Just tried this, but it ends up just displaying `undefined`

![screenshot 2015-02-13 15 02 43](https://cloud.githubusercontent.com/assets/255026/6196816/638e5542-b391-11e4-97f4-d79865c26f48.png)

No console errors though.

Code:
```html
<json-formatter open="0" json="angular.copy(event)"></json-formatter>
```

Any ideas?

**Comment by mohsen1** [comment]
I don't know what's going on in your application. Please do the conversion in your controller. You can also use `angular.toJson(source);`

**Comment by Skinner927** [comment]
`angular.copy()` produces the same `undefined` issue for me too.

**Comment by mohsen1** [comment]
To be fair, it's not JSON Formatter's job to get rid of `$$hashKey`. Maybe there is a case that user wants to show the hash key. I recommend processing your JSON before passing it to JSON Formatter.

**Comment by andrewboni** [comment]
@mohsen1 went with your suggestion, as I agree that it shouldn't necessarily be JSON formatter's job to remove unwanted fields.

I implemented a function like so:
```coffeescript
    $scope.removeHashkey = (event) ->
      _.omit event, ['$$hashKey']
```

and used it as follows:
```html
<json-formatter open="1" json="removeHashKey(event)"></json-formatter>
```

It worked, but only partially, as it was triggering an `Infinite digest` error: https://docs.angularjs.org/error/$rootScope/infdig

This is because I have a table of 10+ rows of events, each using the `json-formatter` directive and calling `removeHashKey()`.

For anyone else in the same situation as me (a table with many rows calling `json-formatter`), I just ended up making one copy of the entire array of objects, cleaned it, and then manually accessed each object in the array like so:
```html
<json-formatter open="1" json="cleanedEventsMap[$index + (tablePageNumber-1) * tablePageSize]"></json-formatter>
```

@mohsen1 maybe `json-formatter` can implement some sort of exclude functionality? Could look something like this:
```html
<json-formatter json="event" exclude="['$$hashKey','otherUnwantedField','unwanted.nestedField']"></json-formatter>
 ```
Thoughts?

**Comment by Rleahy22** [comment]
+1

**Comment by mohsen1** [comment]
Internally it will not add `$$hashKey` anymore(7b34ddd) 

If you are iterating in an array of objects using `ng-repeat`, make sure you are using `track by $index` to avoid adding extra `$$hashKey` to your objects.


I've added the docs [here](https://github.com/mohsen1/json-formatter#hashkey) and in the [examples](http://azimi.me/json-formatter/demo/demo.html) under `ng-repeat` section.
