### ISSUE TITLE
Publish to NPM plus support for Webpack + CommonJS Package Manager

### ISSUE THREAD

**Issue by benoror** [mohsen1/json-formatter#27]
# Motivation

Hi!

I'm in the process of refactoring an app to support modern JS tooling like NPM(-only), Webpack & ES6.

# Code Change

A small change is needed to support CommonJS.:

```
/* commonjs package manager support (eg componentjs) */
if (typeof module !== "undefined" && typeof exports !== "undefined" && module.exports === exports){
  module.exports = 'jsonFormatter';
}
```
* Source: [ui-router release](https://github.com/angular-ui/ui-router/blob/master/release/angular-ui-router.js#L9)
* Or: [UMD (Universal Module Definition)](https://github.com/umdjs/umd)

# Working Examples

I have done other PRs for some of my dependencies:

* https://github.com/wix/angular-tree-control/pull/152
* https://github.com/gdi2290/angular-md5/issues/8
  * https://github.com/gdi2290/angular-md5/pull/9
* https://github.com/muratcorlu/angular-urlify/pull/1
* https://github.com/tarkanlar/Angular-Urlify/pull/1

# Sources

* [Using Angular 1.x With ES6 and Webpack by Jesus Rodriguez](http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/)
* [Webpack & Angular by Shawn McKay ](http://www.shmck.com/webpack-angular-part-3/)
* [Angular and Webpack for Modular Applications by @kentcdodds](https://egghead.io/series/angular-and-webpack-for-modular-applications)
* [NPM for Everything](http://beletsky.net/2015/04/npm-for-everything.html)

**Comment by benoror** [comment]
Update: I just found the package already in npmjs: https://www.npmjs.com/package/jsonformatter

I will PR the README.md accordingly

**Comment by mohsen1** [comment]
I completely agree. Bower is redundant and unnecessary. I'm actually in process of getting rid of Bower in my projects.

**Comment by mohsen1** [comment]
But I don't think you need CommonJS style exports for AngularJS directives since it uses `angular` global object to define an AngularJS module. 
When I refactor this for AngularJS 2 I will make sure to use ES6 `export` to make it play nicely with Angular2

**Comment by benoror** [comment]
:+1: Ok cool!

**Comment by Den-dp** [comment]
@mohsen1 Hi, If you don't want to have changes in `json-formatter.js` I can suggest you another unobtrusive solution with CommonJS-related code in `index.js`.

I'm asking for this because now I'm blocked to use this angular module with webpack.

**Comment by benoror** [comment]
@Den-dp I was able to use it in webpack with (es6 sugar):

```
import jsonFormatter from 'jsonformatter';
import 'jsonformatter/dist/json-formatter.css';

/**...**/

export default angular.module('myModule', [
    'jsonFormatter'
    /**...**/
  ])
```

My [webpack.config.js](https://gist.github.com/benoror/4eff30e975c406b3d7b8)

Idea taken mainly from: http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/

**Comment by Den-dp** [comment]
@benoror Thank you for the quick reply.

There is the convention that all external modules are following is to simply export the name of the module.

If you look at the end of "Config functions" paragraph of your article you will find a good example of the use of the angular module in ES6.

With that in mind after my PR the code above can be rewritten as following
```
import jsonFormatter from 'jsonformatter';
import 'jsonformatter/dist/json-formatter.css';

/**...**/

export default angular.module('myModule', [
    jsonFormatter //<--
    /**...**/
  ])
```

Notice that there are no hardcoded strings in deps array

**Comment by benoror** [comment]
Exactly, that's what meant in my [first post :point_up:](https://github.com/mohsen1/json-formatter/issues/27#issue-102171435) and advocate for :smile: 

What I am saying is that you can temporarily use the string for the modules that don't yet support that convention

**Comment by Den-dp** [comment]
@benoror Yes, I understand that our solutions were more less equal… just tried to suggest another way to solve this issue.

> What I am saying is that you can temporarily use the string for the modules that don't yet support that convention

I know. The only thing that unclear for me is why we can't have those changes now and why we should use workarounds with strings :)

**Comment by benoror** [comment]
Completely agree :wink:
