### ISSUE TITLE
in my project,the css style "content: "►";" would show like this "??"

### ISSUE THREAD

**Issue by figot** [mohsen1/json-formatter#36]
.json-formatter-row .toggler:after {
  display: inline-block;
  transition: transform 100ms ease-in;
  content: "►";
}

the result is "??"

**Comment by mingyang91** [comment]
Probably because you do not have this font(►) in font-family.

(字体中有这个字形吗?)

**Comment by mohsen1** [comment]
Add charset=utf8 to your html
