### ISSUE TITLE
Angular 1.5

### ISSUE THREAD

**Issue by hristozov** [mohsen1/json-formatter#46]
This module seems to work correctly with Angular 1.5, but Bower shows warnings when installing it, because the version (`~1.4.4`) specified in `bower.json`.

Can we change it to allow Angular 1.5?

**Comment by mohsen1** [comment]
https://github.com/mohsen1/json-formatter/releases/tag/v0.5.0

**Comment by hristozov** [comment]
You're awesome. Thanks!

**Comment by mohsen1** [comment]
Thank you!
