### ISSUE TITLE
Check license

### ISSUE THREAD

**Issue by pvnr0082t** [mohsen1/json-formatter#49]
Hi @mohsen1 ,
I would like to add this library to [cdnjs](https://github.com/cdnjs/cdnjs) via send pull request.
I found that the license for this repo is ```Apache 2.0```, but the license info in ```package.json``` and main files is  ```MIT```. Could you tell me the license you use exactly? Thank you.

https://github.com/cdnjs/cdnjs/issues/7594

**Comment by mohsen1** [comment]
License is Apache 2.0. `package.json` is wrong. I'll fix it.

**Comment by pvnr0082t** [comment]
Okay, thank you for your help.

**Comment by mohsen1** [comment]
A PR to fix it is welcome
