### ISSUE TITLE
The version of main files does not match the git tags

### ISSUE THREAD

**Issue by pvnr0082t** [mohsen1/json-formatter#53]
Hi @mohsen1 ,
The autoupdate in [cdnjs](https://github.com/cdnjs/cdnjs) grab files relies on __git tags__. But I found that each version info of main files does not match the git tags. Could you please fix it?
Thank you.

https://github.com/cdnjs/cdnjs/issues/7594
https://github.com/cdnjs/cdnjs/pull/7718

**Comment by mohsen1** [comment]
Hi

I should cut a new release to fix it. Will do tonight PST

**Comment by mohsen1** [comment]
https://github.com/mohsen1/json-formatter/releases/tag/v0.6.0

**Comment by pvnr0082t** [comment]
Hi,
But the version info in __json-formatter.js__, __json-formatter.min.js__, __json-formatter.css__, __json-formatter.min.js__ still show 0.5.0 in [v0.6.0 tagged](https://github.com/mohsen1/json-formatter/tree/v0.6.0/dist)
