### ISSUE TITLE
404 for Angularjs core file

### ISSUE THREAD

**Issue by hkkhchan** [mohsen1/json-formatter#58]
Hi mohsen1,

Thanks for your contribution. but I would like to state that some required angularJS file is not found after I clone the source code though git. I am a starter of web development. I think if I install the plugin with bower. The problem may not existed. 

just a small suggestion. if the source code include the angularjs core file. The demo can run well if the visitor only clone the source code and not install though bower.

**Comment by mohsen1** [comment]
It's usually not a good idea to commit external dependencies in the repository
